### PR TITLE
Fix statistic helper for HA 2022.7+

### PR DESCRIPTION
**Pull request by slovdahl**

### CODE REVIEW

**Comment by slovdahl** [comment]
Tested with latest HA dev as of today and HA 2022.6.7. No errors during startup with either, the sensors seem to work with my Bosch Compress 7001i.

**Comment by slovdahl** [comment]
Alternatively with no version parsing just like this:

```python
try:
    from homeassistant.components.recorder.db_schema import StatisticsMeta
except ImportError:
    from homeassistant.components.recorder.models import StatisticsMeta
```

**Comment by slovdahl** [comment]
Pushed the simpler approach now instead.

**Comment by pszafer** [comment]
Nice 👍

**Pull request merged**
