### PR TITLE
Read DB files asynchronously

### PR DESCRIPTION
**Pull request by slovdahl**
Should solve one of the warnings reported in #420.

See https://github.com/bosch-thermostat/bosch-thermostat-client-python/pull/43.

Fixes warnings in Home Assistant like:

```
2024-06-16 21:44:01.785 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'bosch' at custom_components/bosch/__init__.py, line 303: await self.gateway.check_connection() (offender: /usr/local/lib/python3.12/site-packages/bosch_thermostat_client/db/__init__.py, line 35: with open(file, "r") as db_file:), please create a bug report at https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bosch/__init__.py", line 149, in async_setup_entry
    _init_status: bool = await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 246, in async_init
    if await self.async_init_bosch():
  File "/config/custom_components/bosch/__init__.py", line 303, in async_init_bosch
    await self.gateway.check_connection()
```

### CODE REVIEW

**Comment by slovdahl** [comment]
TODO: Depends on https://github.com/bosch-thermostat/bosch-thermostat-client-python/pull/43 and needs an updated version of it.

**Comment by slovdahl** [comment]
Hm, does this break the integration 🤔 Getting this error in my dev instance now.

```
2024-06-17 19:09:03.798 ERROR (SyncWorker_0) [homeassistant.util.logging] Exception in get_signals when dispatching 'bosch_signal': ()
Traceback (most recent call last):
  File "/workspaces/core/config/custom_components/bosch/__init__.py", line 284, in get_signals
    self.hass.data[DOMAIN][self.uuid][INTERVAL] = async_track_time_interval(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/helpers/event.py", line 1632, in async_track_time_interval
    track.async_attach()
  File "/workspaces/core/homeassistant/helpers/event.py", line 1585, in async_attach
    self._schedule_timer()
  File "/workspaces/core/homeassistant/helpers/event.py", line 1593, in _schedule_timer
    self._timer_handle = loop.call_at(
                         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 776, in call_at
    self._check_thread()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 834, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

**Comment by slovdahl** [comment]
Seems like annotating `get_signals` with `@callback` helped: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/pull/425/commits/146b03299ae7842143f69bb6e104b2f40e2b007c

**Comment by rikroe** [comment]
I think this now works and is ready to review. And required for https://github.com/bosch-thermostat/bosch-thermostat-client-python/pull/43.

**Comment by slovdahl** [comment]
Yep, whenever @pszafer has the time to cut a new release I will update the PR and test it one more time.

**Comment by rikroe** [comment]
Ah sorry mixed up the component and client repositories and thought "how the hell should this work" 😅

**Comment by slovdahl** [comment]
Seems like https://github.com/bosch-thermostat/bosch-thermostat-client-python/actions/runs/10071130183/job/27840742696 failed, so [v0.25.2-dev.1](https://github.com/bosch-thermostat/bosch-thermostat-client-python/releases/tag/v0.25.2-dev.1) is not yet available from pypi.org.

**Comment by slovdahl** [comment]
Turns out this is a requirement for HA 2024.8 too. I did not get any data to my dev HA without these changes applied on top of 0.26.0.

**Pull request merged**
